"""update users table

Revision ID: 0a63bf4c9c4e
Revises: 737ddd5a5c33
Create Date: 2025-02-02 08:43:23.016458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a63bf4c9c4e'
down_revision: Union[str, None] = '737ddd5a5c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_account_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_account_id')
    op.drop_table('main_role')
    op.add_column('users', sa.Column('role_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_code')
    op.create_table('main_role',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main_role_pkey')
    )
    op.add_column('users', sa.Column('role_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_role_account_id_fkey', 'users', 'main_role', ['role_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
