"""add relationship date table

Revision ID: 7aa09931af21
Revises: 08eddeeba46b
Create Date: 2025-01-10 09:30:23.777391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa09931af21'
down_revision: Union[str, None] = '08eddeeba46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dates', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'facebook_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'facebook_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'dates', type_='foreignkey')
    # ### end Alembic commands ###
